// All race results and picks for Weeks 1-8, extracted from official NASCAR statistics PDFs

// Track types for reference
// W1: Daytona = superspeedway (x1.0)
// W2: Atlanta = superspeedway (x1.0)
// W3: COTA = road_course (x1.5)
// W4: Phoenix = short_track (x0.2)
// W5: Las Vegas = intermediate (x0.5)
// W6: Darlington = intermediate (x0.5)
// W7: Martinsville = short_track (x0.2)
// W8: Bristol = short_track (x0.2)

export const HISTORICAL_PICKS = {
  w1: {
    bigmonroe:[{driver:"#5 Kyle Larson"},{driver:"#9 Chase Elliott"},{driver:"#1 Ross Chastain"},{driver:"#97 Shane Van Gisbergen"},{driver:"#84 Jimmie Johnson"}],
    monroe:[{driver:"#11 Denny Hamlin"},{driver:"#22 Joey Logano"},{driver:"#2 Austin Cindric"},{driver:"#23 Bubba Wallace"},{driver:"#4 Noah Gragson"}],
    justin:[{driver:"#88 Connor Zilisch"},{driver:"#19 Chase Briscoe"},{driver:"#60 Ryan Preece"},{driver:"#6 Brad Keselowski"},{driver:"#45 Tyler Reddick"}],
    rich:[{driver:"#24 William Byron"},{driver:"#12 Ryan Blaney"},{driver:"#20 Christopher Bell"},{driver:"#54 Ty Gibbs"},{driver:"#77 Carson Hocevar"}],
  },
  w2: {
    bigmonroe:[{driver:"#24 William Byron"},{driver:"#9 Chase Elliott"},{driver:"#97 Shane Van Gisbergen"},{driver:"#1 Ross Chastain"},{driver:"#2 Austin Cindric"}],
    monroe:[{driver:"#11 Denny Hamlin"},{driver:"#20 Christopher Bell"},{driver:"#23 Bubba Wallace"},{driver:"#17 Chris Buescher"},{driver:"#42 John Hunter Nemechek"}],
    justin:[{driver:"#12 Ryan Blaney"},{driver:"#22 Joey Logano"},{driver:"#19 Chase Briscoe"},{driver:"#77 Carson Hocevar"},{driver:"#48 Alex Bowman"}],
    rich:[{driver:"#88 Connor Zilisch"},{driver:"#5 Kyle Larson"},{driver:"#60 Ryan Preece"},{driver:"#45 Tyler Reddick"},{driver:"#8 Kyle Busch"}],
  },
  w3: {
    bigmonroe:[{driver:"#97 Shane Van Gisbergen"},{driver:"#5 Kyle Larson"},{driver:"#23 Bubba Wallace"},{driver:"#7 Daniel Suarez"},{driver:"#16 AJ Allmendinger"}],
    monroe:[{driver:"#45 Tyler Reddick"},{driver:"#20 Christopher Bell"},{driver:"#77 Carson Hocevar"},{driver:"#71 Michael McDowell"},{driver:"#2 Austin Cindric"}],
    justin:[{driver:"#88 Connor Zilisch"},{driver:"#1 Ross Chastain"},{driver:"#19 Chase Briscoe"},{driver:"#54 Ty Gibbs"},{driver:"#38 Zane Smith"}],
    rich:[{driver:"#9 Chase Elliott"},{driver:"#24 William Byron"},{driver:"#12 Ryan Blaney"},{driver:"#11 Denny Hamlin"},{driver:"#22 Joey Logano"}],
  },
  w4: {
    bigmonroe:[{driver:"#45 Tyler Reddick"},{driver:"#23 Bubba Wallace"},{driver:"#24 William Byron"},{driver:"#71 Michael McDowell"},{driver:"#9 Chase Elliott"}],
    monroe:[{driver:"#11 Denny Hamlin"},{driver:"#17 Chris Buescher"},{driver:"#6 Brad Keselowski"},{driver:"#34 Todd Gilliland"},{driver:"#2 Austin Cindric"}],
    justin:[{driver:"#12 Ryan Blaney"},{driver:"#20 Christopher Bell"},{driver:"#5 Kyle Larson"},{driver:"#77 Carson Hocevar"},{driver:"#19 Chase Briscoe"}],
    rich:[{driver:"#22 Joey Logano"},{driver:"#1 Ross Chastain"},{driver:"#88 Connor Zilisch"},{driver:"#60 Ryan Preece"},{driver:"#54 Ty Gibbs"}],
  },
  w5: {
    rich:[{driver:"#11 Denny Hamlin"},{driver:"#5 Kyle Larson"},{driver:"#24 William Byron"},{driver:"#88 Connor Zilisch"},{driver:"#8 Kyle Busch"}],
    monroe:[{driver:"#22 Joey Logano"},{driver:"#20 Christopher Bell"},{driver:"#23 Bubba Wallace"},{driver:"#21 Josh Berry"},{driver:"#42 John Hunter Nemechek"}],
    bigmonroe:[{driver:"#9 Chase Elliott"},{driver:"#45 Tyler Reddick"},{driver:"#97 Shane Van Gisbergen"},{driver:"#60 Ryan Preece"},{driver:"#47 Ricky Stenhouse Jr"}],
    justin:[{driver:"#12 Ryan Blaney"},{driver:"#77 Carson Hocevar"},{driver:"#1 Ross Chastain"},{driver:"#54 Ty Gibbs"},{driver:"#19 Chase Briscoe"}],
  },
  w6: {
    rich:[{driver:"#24 William Byron"},{driver:"#19 Chase Briscoe"},{driver:"#88 Connor Zilisch"},{driver:"#60 Ryan Preece"},{driver:"#77 Carson Hocevar"}],
    monroe:[{driver:"#5 Kyle Larson"},{driver:"#12 Ryan Blaney"},{driver:"#1 Ross Chastain"},{driver:"#17 Chris Buescher"},{driver:"#38 Zane Smith"}],
    bigmonroe:[{driver:"#11 Denny Hamlin"},{driver:"#45 Tyler Reddick"},{driver:"#23 Bubba Wallace"},{driver:"#97 Shane Van Gisbergen"},{driver:"#2 Austin Cindric"}],
    justin:[{driver:"#20 Christopher Bell"},{driver:"#9 Chase Elliott"},{driver:"#22 Joey Logano"},{driver:"#54 Ty Gibbs"},{driver:"#6 Brad Keselowski"}],
  },
  w7: {
    rich:[{driver:"#11 Denny Hamlin"},{driver:"#45 Tyler Reddick"},{driver:"#19 Chase Briscoe"},{driver:"#77 Carson Hocevar"},{driver:"#60 Ryan Preece"}],
    monroe:[{driver:"#5 Kyle Larson"},{driver:"#20 Christopher Bell"},{driver:"#22 Joey Logano"},{driver:"#17 Chris Buescher"},{driver:"#88 Connor Zilisch"}],
    bigmonroe:[{driver:"#23 Bubba Wallace"},{driver:"#97 Shane Van Gisbergen"},{driver:"#6 Brad Keselowski"},{driver:"#1 Ross Chastain"},{driver:"#2 Austin Cindric"}],
    justin:[{driver:"#12 Ryan Blaney"},{driver:"#9 Chase Elliott"},{driver:"#24 William Byron"},{driver:"#54 Ty Gibbs"},{driver:"#21 Josh Berry"}],
  },
  w8: {
    bigmonroe:[{driver:"#5 Kyle Larson"},{driver:"#54 Ty Gibbs"},{driver:"#23 Bubba Wallace"},{driver:"#6 Brad Keselowski"},{driver:"#20 Christopher Bell"}],
    monroe:[{driver:"#12 Ryan Blaney"},{driver:"#22 Joey Logano"},{driver:"#9 Chase Elliott"},{driver:"#21 Josh Berry",mulligan:true},{driver:"#97 Shane Van Gisbergen"}],
    justin:[{driver:"#19 Chase Briscoe"},{driver:"#77 Carson Hocevar"},{driver:"#45 Tyler Reddick"},{driver:"#7 Daniel Suarez"},{driver:"#88 Connor Zilisch"}],
    rich:[{driver:"#11 Denny Hamlin"},{driver:"#60 Ryan Preece"},{driver:"#17 Chris Buescher"},{driver:"#71 Michael McDowell"},{driver:"#1 Ross Chastain"}],
  },
  w9: {
    justin:[{driver:"#45 Tyler Reddick"},{driver:"#20 Christopher Bell"},{driver:"#54 Ty Gibbs"},{driver:"#17 Chris Buescher"},{driver:"#67 Corey Heim"}],
    bigmonroe:[{driver:"#9 Chase Elliott"},{driver:"#2 Austin Cindric"},{driver:"#23 Bubba Wallace"},{driver:"#8 Kyle Busch"},{driver:"#60 Ryan Preece"}],
    monroe:[{driver:"#5 Kyle Larson"},{driver:"#12 Ryan Blaney"},{driver:"#77 Carson Hocevar"},{driver:"#22 Joey Logano"},{driver:"#6 Brad Keselowski"}],
    rich:[{driver:"#11 Denny Hamlin"},{driver:"#19 Chase Briscoe"},{driver:"#24 William Byron"},{driver:"#1 Ross Chastain"},{driver:"#88 Connor Zilisch"}],
  },
};

// Raw race results - only drivers that matter (picked by at least one player)
// Format: {name, finish, qualPos, stage1, stage2, lapsLed, pole, stageWin1, stageWin2, fastestLap, mostLapsLed, dnf, dq}

export const HISTORICAL_RESULTS = {
  w1: { drivers: [
    // DAYTONA 500 - Superspeedway x1.0
    // S1: 38,2,12,77,7,17,71,60,48,4 | S2: 23,12,42,8,35,67,17,45,22,7 | FL:#77 | Pole:#8 | MostLed:#23(40)
    {name:"#45 Tyler Reddick",finish:1,qualPos:26,stage1:0,stage2:8,lapsLed:1,pole:false,stageWin1:false,stageWin2:false,fastestLap:false,mostLapsLed:false,dnf:false,dq:false},
    {name:"#22 Joey Logano",finish:3,qualPos:3,stage1:0,stage2:9,lapsLed:9,pole:false,stageWin1:false,stageWin2:false,fastestLap:false,mostLapsLed:false,dnf:false,dq:false},
    {name:"#9 Chase Elliott",finish:4,qualPos:4,stage1:0,stage2:0,lapsLed:2,pole:false,stageWin1:false,stageWin2:false,fastestLap:false,mostLapsLed:false,dnf:false,dq:false},
    {name:"#6 Brad Keselowski",finish:5,qualPos:9,stage1:0,stage2:0,lapsLed:0,pole:false,stageWin1:false,stageWin2:false,fastestLap:false,mostLapsLed:false,dnf:false,dq:false},
    {name:"#17 Chris Buescher",finish:7,qualPos:41,stage1:6,stage2:7,lapsLed:4,pole:false,stageWin1:false,stageWin2:false,fastestLap:false,mostLapsLed:false,dnf:false,dq:false},
    {name:"#23 Bubba Wallace",finish:10,qualPos:27,stage1:0,stage2:1,lapsLed:40,pole:false,stageWin1:false,stageWin2:true,fastestLap:false,mostLapsLed:true,dnf:false,dq:false},
    {name:"#4 Noah Gragson",finish:11,qualPos:25,stage1:10,stage2:0,lapsLed:0,pole:false,stageWin1:false,stageWin2:false,fastestLap:false,mostLapsLed:false,dnf:false,dq:false},
    {name:"#24 William Byron",finish:12,qualPos:39,stage1:0,stage2:0,lapsLed:0,pole:false,stageWin1:false,stageWin2:false,fastestLap:false,mostLapsLed:false,dnf:false,dq:false},
    {name:"#7 Daniel Suarez",finish:13,qualPos:15,stage1:5,stage2:10,lapsLed:2,pole:false,stageWin1:false,stageWin2:false,fastestLap:false,mostLapsLed:false,dnf:false,dq:false},
    {name:"#5 Kyle Larson",finish:16,qualPos:8,stage1:0,stage2:0,lapsLed:7,pole:false,stageWin1:false,stageWin2:false,fastestLap:false,mostLapsLed:false,dnf:false,dq:false},
    {name:"#77 Carson Hocevar",finish:18,qualPos:6,stage1:4,stage2:0,lapsLed:1,pole:false,stageWin1:false,stageWin2:false,fastestLap:true,mostLapsLed:false,dnf:false,dq:false},
    {name:"#1 Ross Chastain",finish:20,qualPos:37,stage1:0,stage2:0,lapsLed:12,pole:false,stageWin1:false,stageWin2:false,fastestLap:false,mostLapsLed:false,dnf:false,dq:false},
    {name:"#54 Ty Gibbs",finish:23,qualPos:20,stage1:0,stage2:0,lapsLed:0,pole:false,stageWin1:false,stageWin2:false,fastestLap:false,mostLapsLed:false,dnf:false,dq:false},
    {name:"#60 Ryan Preece",finish:25,qualPos:19,stage1:8,stage2:0,lapsLed:0,pole:false,stageWin1:false,stageWin2:false,fastestLap:false,mostLapsLed:false,dnf:false,dq:false},
    {name:"#12 Ryan Blaney",finish:27,qualPos:5,stage1:3,stage2:2,lapsLed:2,pole:false,stageWin1:false,stageWin2:false,fastestLap:false,mostLapsLed:false,dnf:false,dq:false},
    {name:"#84 Jimmie Johnson",finish:29,qualPos:31,stage1:0,stage2:0,lapsLed:0,pole:false,stageWin1:false,stageWin2:false,fastestLap:false,mostLapsLed:false,dnf:false,dq:false},
    {name:"#97 Shane Van Gisbergen",finish:30,qualPos:13,stage1:0,stage2:0,lapsLed:3,pole:false,stageWin1:false,stageWin2:false,fastestLap:false,mostLapsLed:false,dnf:false,dq:false},
    {name:"#11 Denny Hamlin",finish:31,qualPos:22,stage1:0,stage2:0,lapsLed:3,pole:false,stageWin1:false,stageWin2:false,fastestLap:false,mostLapsLed:false,dnf:false,dq:false},
    {name:"#88 Connor Zilisch",finish:33,qualPos:32,stage1:0,stage2:0,lapsLed:0,pole:false,stageWin1:false,stageWin2:false,fastestLap:false,mostLapsLed:false,dnf:false,dq:false},
    {name:"#2 Austin Cindric",finish:34,qualPos:36,stage1:2,stage2:0,lapsLed:5,pole:false,stageWin1:false,stageWin2:false,fastestLap:false,mostLapsLed:false,dnf:false,dq:false},
    {name:"#20 Christopher Bell",finish:35,qualPos:12,stage1:0,stage2:0,lapsLed:9,pole:false,stageWin1:false,stageWin2:false,fastestLap:false,mostLapsLed:false,dnf:false,dq:false},
    {name:"#19 Chase Briscoe",finish:36,qualPos:2,stage1:0,stage2:0,lapsLed:23,pole:false,stageWin1:false,stageWin2:false,fastestLap:false,mostLapsLed:false,dnf:false,dq:false},
    {name:"#48 Alex Bowman",finish:40,qualPos:21,stage1:9,stage2:0,lapsLed:0,pole:false,stageWin1:false,stageWin2:false,fastestLap:false,mostLapsLed:false,dnf:false,dq:false},
  ]},
  w2: { drivers: [
    // ATLANTA - Superspeedway x1.0
    // S1: 2,23,5,24,9,45,8,22,88,12 | S2: 23,24,19,45,9,77,60,12,6,97 | FL:#41 | Pole:#45(start 1) | MostLed:#45(53)
    {name:"#45 Tyler Reddick",finish:1,qualPos:1,stage1:6,stage2:4,lapsLed:53,pole:true,stageWin1:false,stageWin2:false,fastestLap:false,mostLapsLed:true,dnf:false,dq:false},
    {name:"#19 Chase Briscoe",finish:2,qualPos:34,stage1:0,stage2:3,lapsLed:27,pole:false,stageWin1:false,stageWin2:false,fastestLap:false,mostLapsLed:false,dnf:false,dq:false},
    {name:"#1 Ross Chastain",finish:3,qualPos:21,stage1:0,stage2:0,lapsLed:0,pole:false,stageWin1:false,stageWin2:false,fastestLap:false,mostLapsLed:false,dnf:false,dq:false},
    {name:"#77 Carson Hocevar",finish:4,qualPos:15,stage1:0,stage2:6,lapsLed:2,pole:false,stageWin1:false,stageWin2:false,fastestLap:false,mostLapsLed:false,dnf:false,dq:false},
    {name:"#97 Shane Van Gisbergen",finish:6,qualPos:28,stage1:10,stage2:0,lapsLed:1,pole:false,stageWin1:false,stageWin2:false,fastestLap:false,mostLapsLed:false,dnf:false,dq:false},
    {name:"#23 Bubba Wallace",finish:8,qualPos:9,stage1:2,stage2:1,lapsLed:46,pole:false,stageWin1:false,stageWin2:true,fastestLap:false,mostLapsLed:false,dnf:false,dq:false},
    {name:"#60 Ryan Preece",finish:9,qualPos:26,stage1:0,stage2:7,lapsLed:0,pole:false,stageWin1:false,stageWin2:false,fastestLap:false,mostLapsLed:false,dnf:false,dq:false},
    {name:"#12 Ryan Blaney",finish:10,qualPos:22,stage1:10,stage2:8,lapsLed:6,pole:false,stageWin1:false,stageWin2:false,fastestLap:false,mostLapsLed:false,dnf:false,dq:false},
    {name:"#9 Chase Elliott",finish:11,qualPos:4,stage1:5,stage2:5,lapsLed:11,pole:false,stageWin1:false,stageWin2:false,fastestLap:false,mostLapsLed:false,dnf:false,dq:false},
    {name:"#11 Denny Hamlin",finish:13,qualPos:29,stage1:0,stage2:0,lapsLed:10,pole:false,stageWin1:false,stageWin2:false,fastestLap:false,mostLapsLed:false,dnf:false,dq:false},
    {name:"#17 Chris Buescher",finish:15,qualPos:7,stage1:0,stage2:0,lapsLed:0,pole:false,stageWin1:false,stageWin2:false,fastestLap:false,mostLapsLed:false,dnf:false,dq:false},
    {name:"#6 Brad Keselowski",finish:17,qualPos:5,stage1:9,stage2:0,lapsLed:10,pole:false,stageWin1:false,stageWin2:false,fastestLap:false,mostLapsLed:false,dnf:false,dq:false},
    {name:"#22 Joey Logano",finish:18,qualPos:2,stage1:8,stage2:0,lapsLed:26,pole:false,stageWin1:false,stageWin2:false,fastestLap:false,mostLapsLed:false,dnf:false,dq:false},
    {name:"#42 John Hunter Nemechek",finish:19,qualPos:24,stage1:0,stage2:0,lapsLed:0,pole:false,stageWin1:false,stageWin2:false,fastestLap:false,mostLapsLed:false,dnf:false,dq:false},
    {name:"#20 Christopher Bell",finish:21,qualPos:32,stage1:0,stage2:0,lapsLed:9,pole:false,stageWin1:false,stageWin2:false,fastestLap:false,mostLapsLed:false,dnf:false,dq:false},
    {name:"#48 Alex Bowman",finish:23,qualPos:36,stage1:0,stage2:0,lapsLed:0,pole:false,stageWin1:false,stageWin2:false,fastestLap:false,mostLapsLed:false,dnf:false,dq:false},
    {name:"#2 Austin Cindric",finish:26,qualPos:30,stage1:1,stage2:0,lapsLed:21,pole:false,stageWin1:true,stageWin2:false,fastestLap:false,mostLapsLed:false,dnf:false,dq:false},
    {name:"#24 William Byron",finish:28,qualPos:13,stage1:4,stage2:2,lapsLed:25,pole:false,stageWin1:false,stageWin2:false,fastestLap:false,mostLapsLed:false,dnf:false,dq:false},
    {name:"#88 Connor Zilisch",finish:30,qualPos:31,stage1:9,stage2:0,lapsLed:9,pole:false,stageWin1:false,stageWin2:false,fastestLap:false,mostLapsLed:false,dnf:false,dq:false},
    {name:"#5 Kyle Larson",finish:32,qualPos:16,stage1:3,stage2:0,lapsLed:48,pole:false,stageWin1:false,stageWin2:false,fastestLap:false,mostLapsLed:false,dnf:false,dq:false},
    {name:"#8 Kyle Busch",finish:34,qualPos:14,stage1:7,stage2:0,lapsLed:0,pole:false,stageWin1:false,stageWin2:false,fastestLap:false,mostLapsLed:false,dnf:false,dq:false},
    {name:"#47 Ricky Stenhouse Jr",finish:36,qualPos:3,stage1:0,stage2:0,lapsLed:0,pole:false,stageWin1:false,stageWin2:false,fastestLap:false,mostLapsLed:false,dnf:false,dq:false},
  ]},
  w3: { drivers: [
    // COTA - Road Course x1.5
    // S1: 1,97,71,17,16,54,48,9,77,11 | S2: 54,16,7,34,45,23,12,41,24,97 | FL:#1 | Pole:#45(start 1) | MostLed:#45(58)
    {name:"#45 Tyler Reddick",finish:1,qualPos:1,stage1:0,stage2:5,lapsLed:58,pole:true,stageWin1:false,stageWin2:false,fastestLap:false,mostLapsLed:true,dnf:false,dq:false},
    {name:"#97 Shane Van Gisbergen",finish:2,qualPos:13,stage1:2,stage2:10,lapsLed:2,pole:false,stageWin1:false,stageWin2:false,fastestLap:false,mostLapsLed:false,dnf:false,dq:false},
    {name:"#20 Christopher Bell",finish:3,qualPos:8,stage1:0,stage2:0,lapsLed:0,pole:false,stageWin1:false,stageWin2:false,fastestLap:false,mostLapsLed:false,dnf:false,dq:false},
    {name:"#54 Ty Gibbs",finish:4,qualPos:9,stage1:6,stage2:1,lapsLed:5,pole:false,stageWin1:false,stageWin2:true,fastestLap:false,mostLapsLed:false,dnf:false,dq:false},
    {name:"#71 Michael McDowell",finish:5,qualPos:6,stage1:3,stage2:0,lapsLed:5,pole:false,stageWin1:false,stageWin2:false,fastestLap:false,mostLapsLed:false,dnf:false,dq:false},
    {name:"#5 Kyle Larson",finish:6,qualPos:15,stage1:0,stage2:0,lapsLed:0,pole:false,stageWin1:false,stageWin2:false,fastestLap:false,mostLapsLed:false,dnf:false,dq:false},
    {name:"#9 Chase Elliott",finish:7,qualPos:5,stage1:8,stage2:0,lapsLed:0,pole:false,stageWin1:false,stageWin2:false,fastestLap:false,mostLapsLed:false,dnf:false,dq:false},
    {name:"#12 Ryan Blaney",finish:8,qualPos:4,stage1:0,stage2:7,lapsLed:11,pole:false,stageWin1:false,stageWin2:false,fastestLap:false,mostLapsLed:false,dnf:false,dq:false},
    {name:"#16 AJ Allmendinger",finish:9,qualPos:7,stage1:5,stage2:2,lapsLed:1,pole:false,stageWin1:false,stageWin2:false,fastestLap:false,mostLapsLed:false,dnf:false,dq:false},
    {name:"#11 Denny Hamlin",finish:10,qualPos:19,stage1:10,stage2:0,lapsLed:0,pole:false,stageWin1:false,stageWin2:false,fastestLap:false,mostLapsLed:false,dnf:false,dq:false},
    {name:"#23 Bubba Wallace",finish:11,qualPos:24,stage1:0,stage2:6,lapsLed:0,pole:false,stageWin1:false,stageWin2:false,fastestLap:false,mostLapsLed:false,dnf:false,dq:false},
    {name:"#24 William Byron",finish:13,qualPos:10,stage1:0,stage2:9,lapsLed:1,pole:false,stageWin1:false,stageWin2:false,fastestLap:false,mostLapsLed:false,dnf:false,dq:false},
    {name:"#88 Connor Zilisch",finish:14,qualPos:25,stage1:0,stage2:0,lapsLed:0,pole:false,stageWin1:false,stageWin2:false,fastestLap:false,mostLapsLed:false,dnf:false,dq:false},
    {name:"#22 Joey Logano",finish:15,qualPos:20,stage1:0,stage2:0,lapsLed:0,pole:false,stageWin1:false,stageWin2:false,fastestLap:false,mostLapsLed:false,dnf:false,dq:false},
    {name:"#7 Daniel Suarez",finish:25,qualPos:23,stage1:0,stage2:3,lapsLed:0,pole:false,stageWin1:false,stageWin2:false,fastestLap:false,mostLapsLed:false,dnf:false,dq:false},
    {name:"#77 Carson Hocevar",finish:31,qualPos:12,stage1:9,stage2:0,lapsLed:0,pole:false,stageWin1:false,stageWin2:false,fastestLap:false,mostLapsLed:false,dnf:false,dq:false},
    {name:"#2 Austin Cindric",finish:32,qualPos:28,stage1:0,stage2:0,lapsLed:0,pole:false,stageWin1:false,stageWin2:false,fastestLap:false,mostLapsLed:false,dnf:false,dq:false},
    {name:"#38 Zane Smith",finish:33,qualPos:11,stage1:0,stage2:0,lapsLed:0,pole:false,stageWin1:false,stageWin2:false,fastestLap:false,mostLapsLed:false,dnf:false,dq:false},
    {name:"#1 Ross Chastain",finish:35,qualPos:2,stage1:1,stage2:0,lapsLed:4,pole:false,stageWin1:true,stageWin2:false,fastestLap:true,mostLapsLed:false,dnf:false,dq:false},
    {name:"#19 Chase Briscoe",finish:37,qualPos:3,stage1:0,stage2:0,lapsLed:8,pole:false,stageWin1:false,stageWin2:false,fastestLap:false,mostLapsLed:false,dnf:true,dq:false},
    {name:"#8 Kyle Busch",finish:12,qualPos:30,stage1:0,stage2:0,lapsLed:0,pole:false,stageWin1:false,stageWin2:false,fastestLap:false,mostLapsLed:false,dnf:false,dq:false},
    {name:"#17 Chris Buescher",finish:24,qualPos:14,stage1:4,stage2:0,lapsLed:0,pole:false,stageWin1:false,stageWin2:false,fastestLap:false,mostLapsLed:false,dnf:false,dq:false},
    {name:"#34 Todd Gilliland",finish:21,qualPos:17,stage1:0,stage2:4,lapsLed:0,pole:false,stageWin1:false,stageWin2:false,fastestLap:false,mostLapsLed:false,dnf:false,dq:false},
  ]},
  w4: { drivers: [
    // PHOENIX - Short Track x0.2
    // S1: 12,20,22,45,11,2,7,54,24,1 | S2: 20,11,22,17,23,2,77,45,5,34 | FL:#22 | Pole:#22(start 1) | MostLed:#20(176)
    {name:"#12 Ryan Blaney",finish:1,qualPos:5,stage1:1,stage2:0,lapsLed:28,pole:false,stageWin1:true,stageWin2:false,fastestLap:false,mostLapsLed:false,dnf:false,dq:false},
    {name:"#20 Christopher Bell",finish:2,qualPos:12,stage1:2,stage2:1,lapsLed:176,pole:false,stageWin1:false,stageWin2:true,fastestLap:false,mostLapsLed:true,dnf:false,dq:false},
    {name:"#5 Kyle Larson",finish:3,qualPos:2,stage1:0,stage2:9,lapsLed:0,pole:false,stageWin1:false,stageWin2:false,fastestLap:false,mostLapsLed:false,dnf:false,dq:false},
    {name:"#54 Ty Gibbs",finish:4,qualPos:14,stage1:8,stage2:0,lapsLed:12,pole:false,stageWin1:false,stageWin2:false,fastestLap:false,mostLapsLed:false,dnf:false,dq:false},
    {name:"#11 Denny Hamlin",finish:5,qualPos:11,stage1:5,stage2:2,lapsLed:5,pole:false,stageWin1:false,stageWin2:false,fastestLap:false,mostLapsLed:false,dnf:false,dq:false},
    {name:"#23 Bubba Wallace",finish:6,qualPos:28,stage1:0,stage2:5,lapsLed:0,pole:false,stageWin1:false,stageWin2:false,fastestLap:false,mostLapsLed:false,dnf:false,dq:false},
    {name:"#24 William Byron",finish:7,qualPos:9,stage1:9,stage2:0,lapsLed:1,pole:false,stageWin1:false,stageWin2:false,fastestLap:false,mostLapsLed:false,dnf:false,dq:false},
    {name:"#45 Tyler Reddick",finish:8,qualPos:8,stage1:4,stage2:8,lapsLed:0,pole:false,stageWin1:false,stageWin2:false,fastestLap:false,mostLapsLed:false,dnf:false,dq:false},
    {name:"#71 Michael McDowell",finish:9,qualPos:16,stage1:0,stage2:0,lapsLed:0,pole:false,stageWin1:false,stageWin2:false,fastestLap:false,mostLapsLed:false,dnf:false,dq:false},
    {name:"#17 Chris Buescher",finish:14,qualPos:17,stage1:0,stage2:4,lapsLed:0,pole:false,stageWin1:false,stageWin2:false,fastestLap:false,mostLapsLed:false,dnf:false,dq:false},
    {name:"#6 Brad Keselowski",finish:15,qualPos:37,stage1:0,stage2:0,lapsLed:0,pole:false,stageWin1:false,stageWin2:false,fastestLap:false,mostLapsLed:false,dnf:false,dq:false},
    {name:"#60 Ryan Preece",finish:13,qualPos:13,stage1:0,stage2:0,lapsLed:4,pole:false,stageWin1:false,stageWin2:false,fastestLap:false,mostLapsLed:false,dnf:false,dq:false},
    {name:"#77 Carson Hocevar",finish:20,qualPos:7,stage1:0,stage2:7,lapsLed:0,pole:false,stageWin1:false,stageWin2:false,fastestLap:false,mostLapsLed:false,dnf:false,dq:false},
    {name:"#9 Chase Elliott",finish:23,qualPos:26,stage1:0,stage2:0,lapsLed:0,pole:false,stageWin1:false,stageWin2:false,fastestLap:false,mostLapsLed:false,dnf:false,dq:false},
    {name:"#34 Todd Gilliland",finish:12,qualPos:30,stage1:0,stage2:10,lapsLed:0,pole:false,stageWin1:false,stageWin2:false,fastestLap:false,mostLapsLed:false,dnf:false,dq:false},
    {name:"#2 Austin Cindric",finish:34,qualPos:3,stage1:6,stage2:6,lapsLed:0,pole:false,stageWin1:false,stageWin2:false,fastestLap:false,mostLapsLed:false,dnf:false,dq:false},
    {name:"#1 Ross Chastain",finish:28,qualPos:6,stage1:10,stage2:0,lapsLed:0,pole:false,stageWin1:false,stageWin2:false,fastestLap:false,mostLapsLed:false,dnf:false,dq:false},
    {name:"#88 Connor Zilisch",finish:29,qualPos:19,stage1:0,stage2:0,lapsLed:0,pole:false,stageWin1:false,stageWin2:false,fastestLap:false,mostLapsLed:false,dnf:true,dq:false},
    {name:"#22 Joey Logano",finish:31,qualPos:1,stage1:3,stage2:3,lapsLed:73,pole:true,stageWin1:false,stageWin2:false,fastestLap:true,mostLapsLed:false,dnf:false,dq:false},
    {name:"#19 Chase Briscoe",finish:37,qualPos:20,stage1:0,stage2:0,lapsLed:0,pole:false,stageWin1:false,stageWin2:false,fastestLap:false,mostLapsLed:false,dnf:true,dq:false},
    {name:"#21 Josh Berry",finish:32,qualPos:10,stage1:0,stage2:0,lapsLed:13,pole:false,stageWin1:false,stageWin2:false,fastestLap:false,mostLapsLed:false,dnf:false,dq:false},
  ]},
  w5: { drivers: [
    // LAS VEGAS - Intermediate x0.5
    // S1: 20,5,11,54,23,24,60,9,12,45 | S2: 24,5,20,23,11,45,17,60,9,2 | FL:#11 | Pole:#20(start 1)? No, Hamlin won. Start 1 = Bell | MostLed:#11(134)
    {name:"#11 Denny Hamlin",finish:1,qualPos:2,stage1:3,stage2:5,lapsLed:134,pole:false,stageWin1:false,stageWin2:false,fastestLap:true,mostLapsLed:true,dnf:false,dq:false},
    {name:"#9 Chase Elliott",finish:2,qualPos:15,stage1:8,stage2:9,lapsLed:0,pole:false,stageWin1:false,stageWin2:false,fastestLap:false,mostLapsLed:false,dnf:false,dq:false},
    {name:"#24 William Byron",finish:3,qualPos:9,stage1:6,stage2:1,lapsLed:26,pole:false,stageWin1:false,stageWin2:true,fastestLap:false,mostLapsLed:false,dnf:false,dq:false},
    {name:"#20 Christopher Bell",finish:4,qualPos:1,stage1:1,stage2:3,lapsLed:31,pole:true,stageWin1:true,stageWin2:false,fastestLap:false,mostLapsLed:false,dnf:false,dq:false},
    {name:"#54 Ty Gibbs",finish:5,qualPos:3,stage1:4,stage2:0,lapsLed:0,pole:false,stageWin1:false,stageWin2:false,fastestLap:false,mostLapsLed:false,dnf:false,dq:false},
    {name:"#5 Kyle Larson",finish:7,qualPos:5,stage1:2,stage2:2,lapsLed:62,pole:false,stageWin1:false,stageWin2:false,fastestLap:false,mostLapsLed:false,dnf:false,dq:false},
    {name:"#19 Chase Briscoe",finish:8,qualPos:18,stage1:0,stage2:0,lapsLed:0,pole:false,stageWin1:false,stageWin2:false,fastestLap:false,mostLapsLed:false,dnf:false,dq:false},
    {name:"#23 Bubba Wallace",finish:9,qualPos:4,stage1:5,stage2:4,lapsLed:0,pole:false,stageWin1:false,stageWin2:false,fastestLap:false,mostLapsLed:false,dnf:false,dq:false},
    {name:"#6 Brad Keselowski",finish:10,qualPos:28,stage1:0,stage2:0,lapsLed:4,pole:false,stageWin1:false,stageWin2:false,fastestLap:false,mostLapsLed:false,dnf:false,dq:false},
    {name:"#60 Ryan Preece",finish:11,qualPos:8,stage1:7,stage2:8,lapsLed:0,pole:false,stageWin1:false,stageWin2:false,fastestLap:false,mostLapsLed:false,dnf:false,dq:false},
    {name:"#45 Tyler Reddick",finish:13,qualPos:7,stage1:10,stage2:6,lapsLed:0,pole:false,stageWin1:false,stageWin2:false,fastestLap:false,mostLapsLed:false,dnf:false,dq:false},
    {name:"#22 Joey Logano",finish:15,qualPos:21,stage1:0,stage2:0,lapsLed:3,pole:false,stageWin1:false,stageWin2:false,fastestLap:false,mostLapsLed:false,dnf:false,dq:false},
    {name:"#12 Ryan Blaney",finish:16,qualPos:6,stage1:9,stage2:0,lapsLed:5,pole:false,stageWin1:false,stageWin2:false,fastestLap:false,mostLapsLed:false,dnf:false,dq:false},
    {name:"#1 Ross Chastain",finish:17,qualPos:17,stage1:0,stage2:0,lapsLed:0,pole:false,stageWin1:false,stageWin2:false,fastestLap:false,mostLapsLed:false,dnf:false,dq:false},
    {name:"#42 John Hunter Nemechek",finish:21,qualPos:26,stage1:0,stage2:0,lapsLed:0,pole:false,stageWin1:false,stageWin2:false,fastestLap:false,mostLapsLed:false,dnf:false,dq:false},
    {name:"#77 Carson Hocevar",finish:22,qualPos:19,stage1:0,stage2:0,lapsLed:1,pole:false,stageWin1:false,stageWin2:false,fastestLap:false,mostLapsLed:false,dnf:false,dq:false},
    {name:"#8 Kyle Busch",finish:28,qualPos:24,stage1:0,stage2:0,lapsLed:0,pole:false,stageWin1:false,stageWin2:false,fastestLap:false,mostLapsLed:false,dnf:false,dq:false},
    {name:"#21 Josh Berry",finish:31,qualPos:32,stage1:0,stage2:0,lapsLed:0,pole:false,stageWin1:false,stageWin2:false,fastestLap:false,mostLapsLed:false,dnf:false,dq:false},
    {name:"#88 Connor Zilisch",finish:32,qualPos:25,stage1:0,stage2:0,lapsLed:0,pole:false,stageWin1:false,stageWin2:false,fastestLap:false,mostLapsLed:false,dnf:false,dq:false},
    {name:"#47 Ricky Stenhouse Jr",finish:29,qualPos:23,stage1:0,stage2:0,lapsLed:0,pole:false,stageWin1:false,stageWin2:false,fastestLap:false,mostLapsLed:false,dnf:false,dq:false},
    {name:"#97 Shane Van Gisbergen",finish:36,qualPos:16,stage1:0,stage2:0,lapsLed:0,pole:false,stageWin1:false,stageWin2:false,fastestLap:false,mostLapsLed:false,dnf:false,dq:false},
    {name:"#17 Chris Buescher",finish:6,qualPos:10,stage1:0,stage2:7,lapsLed:0,pole:false,stageWin1:false,stageWin2:false,fastestLap:false,mostLapsLed:false,dnf:false,dq:false},
    {name:"#2 Austin Cindric",finish:19,qualPos:31,stage1:0,stage2:10,lapsLed:0,pole:false,stageWin1:false,stageWin2:false,fastestLap:false,mostLapsLed:false,dnf:false,dq:false},
    {name:"#38 Zane Smith",finish:14,qualPos:12,stage1:0,stage2:0,lapsLed:0,pole:false,stageWin1:false,stageWin2:false,fastestLap:false,mostLapsLed:false,dnf:false,dq:false},
  ]},
  w6: { drivers: [
    // DARLINGTON - Intermediate x0.5
    // S1: 6,45,12,23,5,17,9,2,7,24 | S2: 6,17,5,19,45,60,24,2,54,7 | FL:#23 | Pole:#45(start 1) | MostLed:#6(142)
    {name:"#45 Tyler Reddick",finish:1,qualPos:1,stage1:2,stage2:5,lapsLed:77,pole:true,stageWin1:false,stageWin2:false,fastestLap:false,mostLapsLed:false,dnf:false,dq:false},
    {name:"#6 Brad Keselowski",finish:2,qualPos:5,stage1:1,stage2:1,lapsLed:142,pole:false,stageWin1:true,stageWin2:true,fastestLap:false,mostLapsLed:true,dnf:false,dq:false},
    {name:"#12 Ryan Blaney",finish:3,qualPos:7,stage1:3,stage2:0,lapsLed:0,pole:false,stageWin1:false,stageWin2:false,fastestLap:false,mostLapsLed:false,dnf:false,dq:false},
    {name:"#77 Carson Hocevar",finish:4,qualPos:16,stage1:0,stage2:0,lapsLed:2,pole:false,stageWin1:false,stageWin2:false,fastestLap:false,mostLapsLed:false,dnf:false,dq:false},
    {name:"#2 Austin Cindric",finish:5,qualPos:12,stage1:8,stage2:8,lapsLed:0,pole:false,stageWin1:false,stageWin2:false,fastestLap:false,mostLapsLed:false,dnf:false,dq:false},
    {name:"#54 Ty Gibbs",finish:6,qualPos:28,stage1:0,stage2:9,lapsLed:1,pole:false,stageWin1:false,stageWin2:false,fastestLap:false,mostLapsLed:false,dnf:false,dq:false},
    {name:"#7 Daniel Suarez",finish:7,qualPos:11,stage1:9,stage2:10,lapsLed:0,pole:false,stageWin1:false,stageWin2:false,fastestLap:false,mostLapsLed:false,dnf:false,dq:false},
    {name:"#24 William Byron",finish:8,qualPos:13,stage1:10,stage2:7,lapsLed:0,pole:false,stageWin1:false,stageWin2:false,fastestLap:false,mostLapsLed:false,dnf:false,dq:false},
    {name:"#17 Chris Buescher",finish:9,qualPos:6,stage1:6,stage2:2,lapsLed:41,pole:false,stageWin1:false,stageWin2:false,fastestLap:false,mostLapsLed:false,dnf:false,dq:false},
    {name:"#11 Denny Hamlin",finish:11,qualPos:9,stage1:0,stage2:0,lapsLed:0,pole:false,stageWin1:false,stageWin2:false,fastestLap:false,mostLapsLed:false,dnf:false,dq:false},
    {name:"#19 Chase Briscoe",finish:12,qualPos:23,stage1:0,stage2:4,lapsLed:4,pole:false,stageWin1:false,stageWin2:false,fastestLap:false,mostLapsLed:false,dnf:false,dq:false},
    {name:"#60 Ryan Preece",finish:13,qualPos:17,stage1:0,stage2:6,lapsLed:0,pole:false,stageWin1:false,stageWin2:false,fastestLap:false,mostLapsLed:false,dnf:false,dq:false},
    {name:"#97 Shane Van Gisbergen",finish:14,qualPos:33,stage1:0,stage2:0,lapsLed:0,pole:false,stageWin1:false,stageWin2:false,fastestLap:false,mostLapsLed:false,dnf:false,dq:false},
    {name:"#9 Chase Elliott",finish:15,qualPos:3,stage1:7,stage2:0,lapsLed:6,pole:false,stageWin1:false,stageWin2:false,fastestLap:false,mostLapsLed:false,dnf:false,dq:false},
    {name:"#1 Ross Chastain",finish:16,qualPos:25,stage1:0,stage2:0,lapsLed:0,pole:false,stageWin1:false,stageWin2:false,fastestLap:false,mostLapsLed:false,dnf:false,dq:false},
    {name:"#88 Connor Zilisch",finish:18,qualPos:32,stage1:0,stage2:0,lapsLed:0,pole:false,stageWin1:false,stageWin2:false,fastestLap:false,mostLapsLed:false,dnf:false,dq:false},
    {name:"#20 Christopher Bell",finish:19,qualPos:22,stage1:0,stage2:0,lapsLed:0,pole:false,stageWin1:false,stageWin2:false,fastestLap:false,mostLapsLed:false,dnf:false,dq:false},
    {name:"#22 Joey Logano",finish:33,qualPos:29,stage1:0,stage2:0,lapsLed:0,pole:false,stageWin1:false,stageWin2:false,fastestLap:false,mostLapsLed:false,dnf:false,dq:false},
    {name:"#23 Bubba Wallace",finish:34,qualPos:2,stage1:4,stage2:0,lapsLed:0,pole:false,stageWin1:false,stageWin2:false,fastestLap:true,mostLapsLed:false,dnf:false,dq:false},
    {name:"#5 Kyle Larson",finish:32,qualPos:4,stage1:5,stage2:3,lapsLed:20,pole:false,stageWin1:false,stageWin2:false,fastestLap:false,mostLapsLed:false,dnf:false,dq:false},
    {name:"#38 Zane Smith",finish:22,qualPos:19,stage1:0,stage2:0,lapsLed:0,pole:false,stageWin1:false,stageWin2:false,fastestLap:false,mostLapsLed:false,dnf:false,dq:false},
  ]},
  w7: { drivers: [
    // MARTINSVILLE - Short Track x0.2
    // S1: 11,24,21,54,2,97,22,12,45,60 | S2: 11,54,22,12,24,2,45,97,5,21 | FL:#11 | Pole:#11(start 1) | MostLed:#11(292)
    {name:"#9 Chase Elliott",finish:1,qualPos:10,stage1:0,stage2:0,lapsLed:84,pole:false,stageWin1:false,stageWin2:false,fastestLap:false,mostLapsLed:false,dnf:false,dq:false},
    {name:"#11 Denny Hamlin",finish:2,qualPos:1,stage1:1,stage2:1,lapsLed:292,pole:true,stageWin1:true,stageWin2:true,fastestLap:true,mostLapsLed:true,dnf:false,dq:false},
    {name:"#22 Joey Logano",finish:3,qualPos:9,stage1:7,stage2:3,lapsLed:0,pole:false,stageWin1:false,stageWin2:false,fastestLap:false,mostLapsLed:false,dnf:false,dq:false},
    {name:"#54 Ty Gibbs",finish:4,qualPos:4,stage1:4,stage2:2,lapsLed:0,pole:false,stageWin1:false,stageWin2:false,fastestLap:false,mostLapsLed:false,dnf:false,dq:false},
    {name:"#24 William Byron",finish:5,qualPos:2,stage1:2,stage2:5,lapsLed:6,pole:false,stageWin1:false,stageWin2:false,fastestLap:false,mostLapsLed:false,dnf:false,dq:false},
    {name:"#12 Ryan Blaney",finish:6,qualPos:12,stage1:8,stage2:4,lapsLed:2,pole:false,stageWin1:false,stageWin2:false,fastestLap:false,mostLapsLed:false,dnf:false,dq:false},
    {name:"#20 Christopher Bell",finish:7,qualPos:11,stage1:0,stage2:0,lapsLed:0,pole:false,stageWin1:false,stageWin2:false,fastestLap:false,mostLapsLed:false,dnf:false,dq:false},
    {name:"#2 Austin Cindric",finish:8,qualPos:6,stage1:5,stage2:6,lapsLed:0,pole:false,stageWin1:false,stageWin2:false,fastestLap:false,mostLapsLed:false,dnf:false,dq:false},
    {name:"#5 Kyle Larson",finish:9,qualPos:13,stage1:0,stage2:9,lapsLed:0,pole:false,stageWin1:false,stageWin2:false,fastestLap:false,mostLapsLed:false,dnf:false,dq:false},
    {name:"#21 Josh Berry",finish:10,qualPos:3,stage1:3,stage2:10,lapsLed:2,pole:false,stageWin1:false,stageWin2:false,fastestLap:false,mostLapsLed:false,dnf:false,dq:false},
    {name:"#97 Shane Van Gisbergen",finish:11,qualPos:5,stage1:6,stage2:8,lapsLed:0,pole:false,stageWin1:false,stageWin2:false,fastestLap:false,mostLapsLed:false,dnf:false,dq:false},
    {name:"#60 Ryan Preece",finish:12,qualPos:17,stage1:10,stage2:0,lapsLed:0,pole:false,stageWin1:false,stageWin2:false,fastestLap:false,mostLapsLed:false,dnf:false,dq:false},
    {name:"#6 Brad Keselowski",finish:13,qualPos:23,stage1:0,stage2:0,lapsLed:0,pole:false,stageWin1:false,stageWin2:false,fastestLap:false,mostLapsLed:false,dnf:false,dq:false},
    {name:"#19 Chase Briscoe",finish:14,qualPos:27,stage1:0,stage2:0,lapsLed:0,pole:false,stageWin1:false,stageWin2:false,fastestLap:false,mostLapsLed:false,dnf:false,dq:false},
    {name:"#45 Tyler Reddick",finish:15,qualPos:8,stage1:9,stage2:7,lapsLed:0,pole:false,stageWin1:false,stageWin2:false,fastestLap:false,mostLapsLed:false,dnf:false,dq:false},
    {name:"#1 Ross Chastain",finish:16,qualPos:18,stage1:0,stage2:0,lapsLed:14,pole:false,stageWin1:false,stageWin2:false,fastestLap:false,mostLapsLed:false,dnf:false,dq:false},
    {name:"#77 Carson Hocevar",finish:17,qualPos:7,stage1:0,stage2:0,lapsLed:0,pole:false,stageWin1:false,stageWin2:false,fastestLap:false,mostLapsLed:false,dnf:false,dq:false},
    {name:"#17 Chris Buescher",finish:19,qualPos:16,stage1:0,stage2:0,lapsLed:0,pole:false,stageWin1:false,stageWin2:false,fastestLap:false,mostLapsLed:false,dnf:false,dq:false},
    {name:"#88 Connor Zilisch",finish:26,qualPos:25,stage1:0,stage2:0,lapsLed:0,pole:false,stageWin1:false,stageWin2:false,fastestLap:false,mostLapsLed:false,dnf:false,dq:false},
    {name:"#23 Bubba Wallace",finish:36,qualPos:15,stage1:0,stage2:0,lapsLed:0,pole:false,stageWin1:false,stageWin2:false,fastestLap:false,mostLapsLed:false,dnf:false,dq:false},
  ]},
  w8: { drivers: [
    // BRISTOL - Short Track x0.2
    // S1: 5,20,12,19,21,11,77,35,23,2 | S2: 5,12,11,77,19,21,54,22,23,2 | FL:#12 | Pole:#12(start 1) | MostLed:#5(284)
    {name:"#54 Ty Gibbs",finish:1,qualPos:5,stage1:0,stage2:7,lapsLed:25,pole:false,stageWin1:false,stageWin2:false,fastestLap:false,mostLapsLed:false,dnf:false,dq:false},
    {name:"#12 Ryan Blaney",finish:2,qualPos:1,stage1:3,stage2:2,lapsLed:190,pole:true,stageWin1:false,stageWin2:false,fastestLap:true,mostLapsLed:false,dnf:false,dq:false},
    {name:"#5 Kyle Larson",finish:3,qualPos:8,stage1:1,stage2:1,lapsLed:284,pole:false,stageWin1:true,stageWin2:true,fastestLap:false,mostLapsLed:true,dnf:false,dq:false},
    {name:"#45 Tyler Reddick",finish:4,qualPos:2,stage1:0,stage2:0,lapsLed:0,pole:false,stageWin1:false,stageWin2:false,fastestLap:false,mostLapsLed:false,dnf:false,dq:false},
    {name:"#19 Chase Briscoe",finish:5,qualPos:3,stage1:4,stage2:5,lapsLed:0,pole:false,stageWin1:false,stageWin2:false,fastestLap:false,mostLapsLed:false,dnf:false,dq:false},
    {name:"#22 Joey Logano",finish:7,qualPos:20,stage1:0,stage2:8,lapsLed:0,pole:false,stageWin1:false,stageWin2:false,fastestLap:false,mostLapsLed:false,dnf:false,dq:false},
    {name:"#60 Ryan Preece",finish:8,qualPos:17,stage1:0,stage2:0,lapsLed:0,pole:false,stageWin1:false,stageWin2:false,fastestLap:false,mostLapsLed:false,dnf:false,dq:false},
    {name:"#11 Denny Hamlin",finish:9,qualPos:11,stage1:6,stage2:3,lapsLed:0,pole:false,stageWin1:false,stageWin2:false,fastestLap:false,mostLapsLed:false,dnf:false,dq:false},
    {name:"#77 Carson Hocevar",finish:10,qualPos:10,stage1:7,stage2:4,lapsLed:0,pole:false,stageWin1:false,stageWin2:false,fastestLap:false,mostLapsLed:false,dnf:false,dq:false},
    {name:"#23 Bubba Wallace",finish:11,qualPos:12,stage1:9,stage2:9,lapsLed:0,pole:false,stageWin1:false,stageWin2:false,fastestLap:false,mostLapsLed:false,dnf:false,dq:false},
    {name:"#7 Daniel Suarez",finish:12,qualPos:13,stage1:0,stage2:0,lapsLed:0,pole:false,stageWin1:false,stageWin2:false,fastestLap:false,mostLapsLed:false,dnf:false,dq:false},
    {name:"#17 Chris Buescher",finish:13,qualPos:17,stage1:0,stage2:0,lapsLed:0,pole:false,stageWin1:false,stageWin2:false,fastestLap:false,mostLapsLed:false,dnf:false,dq:false},
    {name:"#6 Brad Keselowski",finish:14,qualPos:21,stage1:0,stage2:0,lapsLed:0,pole:false,stageWin1:false,stageWin2:false,fastestLap:false,mostLapsLed:false,dnf:false,dq:false},
    {name:"#9 Chase Elliott",finish:22,qualPos:18,stage1:0,stage2:0,lapsLed:0,pole:false,stageWin1:false,stageWin2:false,fastestLap:false,mostLapsLed:false,dnf:false,dq:false},
    {name:"#71 Michael McDowell",finish:24,qualPos:19,stage1:0,stage2:0,lapsLed:0,pole:false,stageWin1:false,stageWin2:false,fastestLap:false,mostLapsLed:false,dnf:false,dq:false},
    {name:"#20 Christopher Bell",finish:27,qualPos:14,stage1:2,stage2:0,lapsLed:6,pole:false,stageWin1:false,stageWin2:false,fastestLap:false,mostLapsLed:false,dnf:false,dq:false},
    {name:"#1 Ross Chastain",finish:20,qualPos:6,stage1:0,stage2:0,lapsLed:0,pole:false,stageWin1:false,stageWin2:false,fastestLap:false,mostLapsLed:false,dnf:false,dq:false},
    {name:"#21 Josh Berry",finish:32,qualPos:25,stage1:5,stage2:6,lapsLed:0,pole:false,stageWin1:false,stageWin2:false,fastestLap:false,mostLapsLed:false,dnf:false,dq:false},
    {name:"#88 Connor Zilisch",finish:33,qualPos:26,stage1:0,stage2:0,lapsLed:0,pole:false,stageWin1:false,stageWin2:false,fastestLap:false,mostLapsLed:false,dnf:false,dq:false},
    {name:"#97 Shane Van Gisbergen",finish:34,qualPos:33,stage1:0,stage2:0,lapsLed:0,pole:false,stageWin1:false,stageWin2:false,fastestLap:false,mostLapsLed:false,dnf:false,dq:false},
    {name:"#2 Austin Cindric",finish:16,qualPos:9,stage1:10,stage2:10,lapsLed:0,pole:false,stageWin1:false,stageWin2:false,fastestLap:false,mostLapsLed:false,dnf:false,dq:false},
  ]},
  w9: { drivers: [
    // KANSAS - Intermediate x0.5
    // S1: 11,5,45,54,20,9,19,77,23,67 | S2: 5,11,45,9,20,23,6,54,17,77 | FL:#20 | Pole:#45(start 1) | MostLed:#11(131)
    {name:"#45 Tyler Reddick",finish:1,qualPos:1,stage1:3,stage2:3,lapsLed:10,pole:true,stageWin1:false,stageWin2:false,fastestLap:false,mostLapsLed:false,dnf:false,dq:false},
    {name:"#5 Kyle Larson",finish:2,qualPos:4,stage1:2,stage2:1,lapsLed:78,pole:false,stageWin1:false,stageWin2:true,fastestLap:false,mostLapsLed:false,dnf:false,dq:false},
    {name:"#19 Chase Briscoe",finish:3,qualPos:5,stage1:7,stage2:0,lapsLed:0,pole:false,stageWin1:false,stageWin2:false,fastestLap:false,mostLapsLed:false,dnf:false,dq:false},
    {name:"#11 Denny Hamlin",finish:4,qualPos:2,stage1:1,stage2:2,lapsLed:131,pole:false,stageWin1:true,stageWin2:false,fastestLap:false,mostLapsLed:true,dnf:false,dq:false},
    {name:"#23 Bubba Wallace",finish:5,qualPos:10,stage1:9,stage2:6,lapsLed:0,pole:false,stageWin1:false,stageWin2:false,fastestLap:false,mostLapsLed:false,dnf:false,dq:false},
    {name:"#6 Brad Keselowski",finish:6,qualPos:21,stage1:0,stage2:7,lapsLed:0,pole:false,stageWin1:false,stageWin2:false,fastestLap:false,mostLapsLed:false,dnf:false,dq:false},
    {name:"#24 William Byron",finish:7,qualPos:14,stage1:0,stage2:0,lapsLed:0,pole:false,stageWin1:false,stageWin2:false,fastestLap:false,mostLapsLed:false,dnf:false,dq:false},
    {name:"#9 Chase Elliott",finish:8,qualPos:13,stage1:6,stage2:4,lapsLed:0,pole:false,stageWin1:false,stageWin2:false,fastestLap:false,mostLapsLed:false,dnf:false,dq:false},
    {name:"#54 Ty Gibbs",finish:9,qualPos:3,stage1:4,stage2:8,lapsLed:0,pole:false,stageWin1:false,stageWin2:false,fastestLap:false,mostLapsLed:false,dnf:false,dq:false},
    {name:"#17 Chris Buescher",finish:10,qualPos:7,stage1:0,stage2:9,lapsLed:1,pole:false,stageWin1:false,stageWin2:false,fastestLap:false,mostLapsLed:false,dnf:false,dq:false},
    {name:"#60 Ryan Preece",finish:11,qualPos:12,stage1:0,stage2:0,lapsLed:0,pole:false,stageWin1:false,stageWin2:false,fastestLap:false,mostLapsLed:false,dnf:false,dq:false},
    {name:"#2 Austin Cindric",finish:12,qualPos:34,stage1:0,stage2:0,lapsLed:0,pole:false,stageWin1:false,stageWin2:false,fastestLap:false,mostLapsLed:false,dnf:false,dq:false},
    {name:"#77 Carson Hocevar",finish:13,qualPos:6,stage1:8,stage2:10,lapsLed:6,pole:false,stageWin1:false,stageWin2:false,fastestLap:false,mostLapsLed:false,dnf:false,dq:false},
    {name:"#67 Corey Heim",finish:15,qualPos:24,stage1:10,stage2:0,lapsLed:0,pole:false,stageWin1:false,stageWin2:false,fastestLap:false,mostLapsLed:false,dnf:false,dq:false},
    {name:"#20 Christopher Bell",finish:20,qualPos:11,stage1:5,stage2:5,lapsLed:47,pole:false,stageWin1:false,stageWin2:false,fastestLap:true,mostLapsLed:false,dnf:false,dq:false},
    {name:"#12 Ryan Blaney",finish:24,qualPos:9,stage1:0,stage2:0,lapsLed:0,pole:false,stageWin1:false,stageWin2:false,fastestLap:false,mostLapsLed:false,dnf:false,dq:false},
    {name:"#1 Ross Chastain",finish:26,qualPos:31,stage1:0,stage2:0,lapsLed:0,pole:false,stageWin1:false,stageWin2:false,fastestLap:false,mostLapsLed:false,dnf:false,dq:false},
    {name:"#88 Connor Zilisch",finish:29,qualPos:36,stage1:0,stage2:0,lapsLed:0,pole:false,stageWin1:false,stageWin2:false,fastestLap:false,mostLapsLed:false,dnf:false,dq:false},
    {name:"#22 Joey Logano",finish:30,qualPos:15,stage1:0,stage2:0,lapsLed:0,pole:false,stageWin1:false,stageWin2:false,fastestLap:false,mostLapsLed:false,dnf:false,dq:false},
    {name:"#8 Kyle Busch",finish:35,qualPos:23,stage1:0,stage2:0,lapsLed:0,pole:false,stageWin1:false,stageWin2:false,fastestLap:false,mostLapsLed:false,dnf:false,dq:false},
    {name:"#7 Daniel Suarez",finish:19,qualPos:8,stage1:0,stage2:0,lapsLed:1,pole:false,stageWin1:false,stageWin2:false,fastestLap:false,mostLapsLed:false,dnf:false,dq:false},
  ]},
};
